# Generated by Django 2.0.6 on 2018-06-09 21:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(blank=True, max_length=50, null=True, verbose_name='Категория')),
                ('price_per_month', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Цена за месяц, руб.')),
                ('price_per_day', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Цена за день, руб.')),
                ('price_per_hour', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Цена за час, руб.')),
            ],
            options={
                'verbose_name': 'Категория',
                'verbose_name_plural': 'Категории',
            },
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=500, null=True, verbose_name='Описание')),
                ('price_per_month', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Цена за месяц, руб.')),
                ('price_per_day', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Цена за день, руб.')),
                ('price_per_hour', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Цена за час, руб.')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='renta_app.Category', verbose_name='Категория')),
            ],
            options={
                'verbose_name': 'Объект',
                'verbose_name_plural': 'Объекты',
            },
        ),
    ]
