# Generated by Django 2.0.6 on 2018-06-09 22:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('renta_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='img',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Ссылка на изображение'),
        ),
        migrations.AddField(
            model_name='item',
            name='img',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Ссылка на изображение'),
        ),
    ]
