# Generated by Django 2.0.6 on 2018-06-13 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('renta_app', '0002_auto_20180610_0130'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='quantity',
            field=models.PositiveSmallIntegerField(blank=True, default=1, null=True, verbose_name='Цена за час, руб.'),
        ),
        migrations.AlterField(
            model_name='category',
            name='price_per_day',
            field=models.PositiveSmallIntegerField(blank=True, default=0, null=True, verbose_name='Цена за день, руб.'),
        ),
        migrations.AlterField(
            model_name='category',
            name='price_per_hour',
            field=models.PositiveSmallIntegerField(blank=True, default=0, null=True, verbose_name='Цена за час, руб.'),
        ),
        migrations.AlterField(
            model_name='category',
            name='price_per_month',
            field=models.PositiveSmallIntegerField(blank=True, default=0, null=True, verbose_name='Цена за месяц, руб.'),
        ),
    ]
