# Generated by Django 2.0.6 on 2018-06-13 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('renta_app', '0004_auto_20180613_2146'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='description',
            field=models.TextField(blank=True, default=1, null=True, verbose_name='Описание'),
        ),
    ]
